language: r
sudo: required
r_github_packages:
  - da-ta-vinci21/Rperform
  - yihui/knitr

env:
  global:
  - secure: "Wy8RDFyW7NO+V86Izh3AyOgcJGVTd2ja6SA4lcizeLLnRJH85lZP63S64jj0qd/1BpGb8EdFrbpiCzRujAh87qek0YkrWtvupDlbPiAqISmhKAKZaY8jtyQ++TSdtNMHWdfky/qaxGmGd3uD2QEu1sUKPBpzCAlbo5IvfKERjwU="

before_install:
  - chmod 755 .push_gh_pages.sh

after_success:
  - ./.push_gh_pages.sh